Feature/ayr 139
nationalarchives/da-ayr-terraform-infra pull request #1
Opened 2022-12-19 12:14 UTC by ailkhamov-zaizi

2022-12-19 13:19 UTC, olaapata submitted a review, later dismissed

2022-12-20 09:49 UTC, gmalanga approved these changes, later dismissed

2022-12-20 09:49 UTC, gmalanga commented on .github/workflows/platform-deployment.yml
> +    branches: [feature/AYR-139]
I don't think this is correct, it should be main. Any push to the main has to trigger the workflow.

2022-12-20 09:49 UTC, gmalanga commented on .github/workflows/platform-deployment.yml
> +    uses: nationalarchives/da-ayr-gthub-actions/.github/workflows/terraform-enviromements-action.yml@feature/AYR-139
Same as the above, I think this should be main and not feature

2022-12-20 10:27 UTC, gmalanga requested changes

2022-12-20 10:27 UTC, gmalanga commented on terraform/environments/dev/providers.tf
> +provider "aws" {
Why do we require another provider? I think you should remove this one.

2022-12-20 10:37 UTC, gmalanga commented on terraform/environments/dev/main.tf
> +  providers = {
This provider should be removed

2022-12-20 10:40 UTC, gmalanga submitted a review, later dismissed

2022-12-20 11:18 UTC, gmalanga approved these changes

2023-03-08 10:45 UTC, closed without merging